import Head from "next/head";
import Page from "@/components/Page/Page";
import { EN_US as lang } from "@/lang/en-US";
import { Nav } from "@/components/Nav/NavStyled";
import { NavContainer } from "@/components/Container/ContainerStyled";
import { Jumbo } from "@/components/Jumbo/Jumbo";
import { upper } from "@/util/util";
import { Footer } from "@/components/Footer/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>{lang.siteName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavContainer>
          <h2>{lang.author} | Portfolio</h2>
          <Nav>
            <ul>
              {lang.nav.map((item, index) => (
                <li key={index}>
                  <a href={item.url}>{upper(item.name)}</a>
                </li>
              ))}
            </ul>
          </Nav>
        </NavContainer>
        <Jumbo />
      </main>
      <Footer />
    </>
  );
}
